# Generated by Django 5.1.4 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(max_length=255)),
                ('path_audio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
