# Generated by Django 5.1.4 on 2025-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='description',
            field=models.TextField(),
        ),
    ]
