# Generated by Django 5.1.4 on 2025-01-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_newsdata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='text',
            field=models.TextField(default='sadklfdjf'),
            preserve_default=False,
        ),
    ]
