# Generated by Django 5.1.4 on 2025-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_newsdata_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
