# Generated by Django 5.1.4 on 2025-01-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_newsdata_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
